/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import view.utils.*;
import model.Controller;
import model.IAutor;
import model.IController;


public class TelaAutores extends BaseWindow {

    /**
     * Creates new form TelaColaboradores
     */
    public TelaAutores() {
        super(null);
        initComponents();
        jPanel = jPanelFundo;
        aplicarConfiguracoes();
        carregarImagem(lb_voltar, "voltar.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        bt_deletarPorId = new javax.swing.JButton();
        bt_deletarSelecionado = new javax.swing.JButton();
        bt_cadastrarColaborador = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        bt_buscarPorId = new javax.swing.JButton();
        bt_buscarTodos = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        bt_alterarPorId = new javax.swing.JButton();
        bt_alterarSelecionado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lb_voltar = new javax.swing.JLabel();
        bt_voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 1150, 210));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_deletarPorId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_deletarPorId.setText("DELETAR POR ID");
        bt_deletarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletarPorIdActionPerformed(evt);
            }
        });
        jPanel3.add(bt_deletarPorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, 40));

        bt_deletarSelecionado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_deletarSelecionado.setText("DELETAR SELECIONADO");
        bt_deletarSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletarSelecionadoActionPerformed(evt);
            }
        });
        jPanel3.add(bt_deletarSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, 260, 140));

        bt_cadastrarColaborador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_cadastrarColaborador.setText("CADASTRAR");
        bt_cadastrarColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarColaboradorActionPerformed(evt);
            }
        });
        jPanel1.add(bt_cadastrarColaborador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 180, 140));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_buscarPorId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_buscarPorId.setText("BUSCAR POR ID");
        bt_buscarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarPorIdActionPerformed(evt);
            }
        });
        jPanel5.add(bt_buscarPorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, 40));

        bt_buscarTodos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_buscarTodos.setText("BUSCAR TODOS");
        bt_buscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarTodosActionPerformed(evt);
            }
        });
        jPanel5.add(bt_buscarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 260, 140));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_alterarPorId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_alterarPorId.setText("ALTERAR POR ID");
        bt_alterarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarPorIdActionPerformed(evt);
            }
        });
        jPanel6.add(bt_alterarPorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, 40));

        bt_alterarSelecionado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_alterarSelecionado.setText("ALTERAR SELECIONADO");
        bt_alterarSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarSelecionadoActionPerformed(evt);
            }
        });
        jPanel6.add(bt_alterarSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 260, 140));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DELETAR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 260, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BUSCAR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 260, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("AUTORES");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 80, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ALTERAR");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 260, 30));

        jPanelFundo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1190, 510));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(lb_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });
        jPanel2.add(bt_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AUTORES");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1210, 80));

        jPanelFundo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 100));

        getContentPane().add(jPanelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        this.setVisible(false);
        TelaMenuLivro.main(null);
    }//GEN-LAST:event_bt_voltarActionPerformed

    private void bt_deletarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletarPorIdActionPerformed
        try {
            
            IController controller = Controller.getInstance();
            int idAutor = getIntFromUser("Digite o id do autor");
            
            if (idAutor == -1) return;
            
            if (! controller.existeAutor(idAutor))
                throw new Exception("Autor não cadastrado!");
            
            controller.removerAutor(idAutor);
            exibirMensagemInformativa("Autor deletado com sucesso");
            
            
        } catch(Exception e) {
            exibirMesagemDeErro(e.getMessage());
        }
    }//GEN-LAST:event_bt_deletarPorIdActionPerformed

    private void bt_deletarSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletarSelecionadoActionPerformed
        try {
            
            if (!exibirMensagemConfirmacao("Tem certeza que deseja excluir o autor?"))
                return;
            
            Iterator<Object> linha = getLinhaSelecionada(table);
            
            if (! linha.hasNext())
            throw new Exception("Selecione um registro primeiro");
            
            int idAutor = Integer.parseInt(linha.next().toString());
            
            IController controller = Controller.getInstance();
            if (! controller.existeAutor(idAutor))
                throw new Exception("Autor não cadastrado!");
            
            controller.removerAutor(idAutor);
            
            exibirMensagemInformativa("Autor deletado com sucesso!");
            
            
        } catch(Exception e) {
            exibirMesagemDeErro(e.getMessage());
        }
    }//GEN-LAST:event_bt_deletarSelecionadoActionPerformed

    private void bt_buscarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarPorIdActionPerformed
        try {
            IController controller = Controller.getInstance();
            int idAutor = getIntFromUser("Digite o id do autor: ");
            if (idAutor == -1) return;
                            
            IAutor autor = controller.getAutor(idAutor);
            listarAutor(table, autor);
            
        } catch(Exception erro) {
            exibirMesagemDeErro(erro.getMessage());
        }
    }//GEN-LAST:event_bt_buscarPorIdActionPerformed

    private void bt_buscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarTodosActionPerformed
        
        try {
            IController controller = Controller.getInstance();
            Iterator<IAutor> autores = controller.getTodosAutores();
            listarAutores(table, autores);
            
        } catch(Exception erro) {
            exibirMesagemDeErro(erro.getMessage());
        }
        
    }//GEN-LAST:event_bt_buscarTodosActionPerformed

    private void bt_alterarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarPorIdActionPerformed
        this.setVisible(false);
        TelaAlterarAutores.main(null);
    }//GEN-LAST:event_bt_alterarPorIdActionPerformed

    private void bt_alterarSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarSelecionadoActionPerformed
        try {        
        Iterator<Object> linha = getLinhaSelecionada(table);
        
        if (! linha.hasNext())
            throw new Exception("Selecione um registro primeiro");
             
        this.setVisible(false);
        TelaAlterarAutores.main(linha.next());
        
        
        } catch(Exception e) {
            exibirMesagemDeErro(e.getMessage());
        }
    }//GEN-LAST:event_bt_alterarSelecionadoActionPerformed

    private void bt_cadastrarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarColaboradorActionPerformed
        this.setVisible(false);
        TelaCadastrarAutores.main(null);
    }//GEN-LAST:event_bt_cadastrarColaboradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAutores().setVisible(true);
            }
        });
    }
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_alterarPorId;
    private javax.swing.JButton bt_alterarSelecionado;
    private javax.swing.JButton bt_buscarPorId;
    private javax.swing.JButton bt_buscarTodos;
    private javax.swing.JButton bt_cadastrarColaborador;
    private javax.swing.JButton bt_deletarPorId;
    private javax.swing.JButton bt_deletarSelecionado;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_voltar;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    @Override
    protected Object[] templedMethodObjectType(Object obj) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }




}
