/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.utils.*;
import java.awt.Image;
import javax.swing.ImageIcon;

public class TelaMenuEmprestimo extends BaseWindow {
        
    
    public TelaMenuEmprestimo() {
        super(null);
        initComponents();        

        setarImagemBotoes();
        jPanel = jPanelFundo;
        aplicarConfiguracoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        lb_voltar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lb_emprestar = new javax.swing.JLabel();
        bt_emprestar = new javax.swing.JButton();
        lb_devolver = new javax.swing.JLabel();
        bt_devolver = new javax.swing.JButton();
        lb_emprestimos = new javax.swing.JLabel();
        bt_livroAtraso = new javax.swing.JButton();
        bt_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelFundo.add(lb_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU EMPRÉSTIMO");
        jPanelFundo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1270, 40));
        jPanelFundo.add(lb_emprestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 170, 110));

        bt_emprestar.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        bt_emprestar.setText("EMPRESTAR");
        bt_emprestar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        bt_emprestar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_emprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_emprestarActionPerformed(evt);
            }
        });
        jPanelFundo.add(bt_emprestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 605, 290));
        jPanelFundo.add(lb_devolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, 170, 110));

        bt_devolver.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        bt_devolver.setText("DEVOLVER");
        bt_devolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        bt_devolver.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_devolverActionPerformed(evt);
            }
        });
        jPanelFundo.add(bt_devolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 605, 290));
        jPanelFundo.add(lb_emprestimos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 170, 110));

        bt_livroAtraso.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        bt_livroAtraso.setText("LIVROS EM ATRASO");
        bt_livroAtraso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        bt_livroAtraso.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_livroAtraso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_livroAtrasoActionPerformed(evt);
            }
        });
        jPanelFundo.add(bt_livroAtraso, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 605, 290));

        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });
        jPanelFundo.add(bt_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        getContentPane().add(jPanelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_devolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_devolverActionPerformed
       
        this.setVisible(false);
        TelaDevolver.main(null);
    }//GEN-LAST:event_bt_devolverActionPerformed

    private void bt_emprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_emprestarActionPerformed
        this.setVisible(false);
        TelaEmprestar.main(null);
    }//GEN-LAST:event_bt_emprestarActionPerformed

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        this.setVisible(false);
        MainWindow.main(null);
    }//GEN-LAST:event_bt_voltarActionPerformed

    private void bt_livroAtrasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_livroAtrasoActionPerformed
        this.setVisible(false);
        TelaLivrosEmAtraso.main(null);
    }//GEN-LAST:event_bt_livroAtrasoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_devolver;
    private javax.swing.JButton bt_emprestar;
    private javax.swing.JButton bt_livroAtraso;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JLabel lb_devolver;
    private javax.swing.JLabel lb_emprestar;
    private javax.swing.JLabel lb_emprestimos;
    private javax.swing.JLabel lb_voltar;
    // End of variables declaration//GEN-END:variables



    private void setarImagemBotoes() {
        try {
            
            carregarImagem(lb_emprestar, "emprestar.png");
            carregarImagem(lb_devolver, "devolver.png");
            carregarImagem(lb_emprestimos, "atraso.png");
            carregarImagem(lb_voltar, "voltar.png");
                        
        } catch (Exception e) {
            exibirMesagemDeErro(e.getMessage());
        }
    }
}
