/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.utils.*;
import java.awt.Image;
import javax.swing.ImageIcon;

public class TelaMenuRemocao extends BaseWindow {

    
    private final String pastaImagem = "./src/view/img/";
    
    public TelaMenuRemocao() {
        super(null);
        initComponents();        

        setarImagemBotoes();
        jPanel = jPanelFundo;
        aplicarConfiguracoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_excluirExemplar = new javax.swing.JLabel();
        bt_excluirExemplar = new javax.swing.JButton();
        lb_absoleto = new javax.swing.JLabel();
        bt_livrosAbsoletos = new javax.swing.JButton();
        lb_voltar = new javax.swing.JLabel();
        bt_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU - REMOVER LIVROS / EXEMPLARES");
        jPanelFundo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1270, 70));
        jPanelFundo.add(lb_excluirExemplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 370, 290));

        bt_excluirExemplar.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        bt_excluirExemplar.setText("EXCLUIR EXEMPLAR");
        bt_excluirExemplar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        bt_excluirExemplar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_excluirExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirExemplarActionPerformed(evt);
            }
        });
        jPanelFundo.add(bt_excluirExemplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 600, 410));
        jPanelFundo.add(lb_absoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 370, 290));

        bt_livrosAbsoletos.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        bt_livrosAbsoletos.setText("LIVROS ABSOLETOS");
        bt_livrosAbsoletos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        bt_livrosAbsoletos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_livrosAbsoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_livrosAbsoletosActionPerformed(evt);
            }
        });
        jPanelFundo.add(bt_livrosAbsoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 600, 410));
        jPanelFundo.add(lb_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });
        jPanelFundo.add(bt_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        getContentPane().add(jPanelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_livrosAbsoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_livrosAbsoletosActionPerformed
        this.setVisible(false);
        TelaLivrosAbsoletos.main(null);
    }//GEN-LAST:event_bt_livrosAbsoletosActionPerformed

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        this.setVisible(false);
        TelaMenuLivro.main(null);
    }//GEN-LAST:event_bt_voltarActionPerformed

    private void bt_excluirExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirExemplarActionPerformed
        this.setVisible(false);
        TelaExemplaresExcluidos.main(null);
    }//GEN-LAST:event_bt_excluirExemplarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuRemocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuRemocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuRemocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuRemocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuRemocao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_excluirExemplar;
    private javax.swing.JButton bt_livrosAbsoletos;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JLabel lb_absoleto;
    private javax.swing.JLabel lb_excluirExemplar;
    private javax.swing.JLabel lb_voltar;
    // End of variables declaration//GEN-END:variables



    private void setarImagemBotoes() {
        try {
            
            carregarImagem(lb_excluirExemplar, "excluirExemplar_512.png");            
            carregarImagem(lb_absoleto, "livroAbsoleto.png");            
            carregarImagem(lb_voltar, "voltar.png");            
                        
        } catch (Exception e) {
            exibirMesagemDeErro(e.getMessage());
        }
    }

    @Override
    protected Object[] templedMethodObjectType(Object obj) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }





}
