/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import view.utils.BaseWindow;

/**
 *
 * @author junio
 */
public class TelaAlterarColaborador extends BaseWindow {

    /**
     * Creates new form TelaAlterarColaborador
     */
    public TelaAlterarColaborador() {
        super(null);
        initComponents();
        jPanel = jPanelFundo;
        aplicarConfiguracoes();
        carregarImagem(lb_voltar, "voltar.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lb_voltar = new javax.swing.JLabel();
        bt_voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_matricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ckb_alterarStatus = new javax.swing.JCheckBox();
        txt_telefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        rb_ativo = new javax.swing.JRadioButton();
        rb_inativo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        ckb_alterarNome = new javax.swing.JCheckBox();
        ckb_alterarTelefone = new javax.swing.JCheckBox();
        ckb_alterarCargo = new javax.swing.JCheckBox();
        cb_cargo = new javax.swing.JComboBox<>();
        lb_cargo = new javax.swing.JLabel();
        ckb_alterarEmail = new javax.swing.JCheckBox();
        txt_numeroOAB = new javax.swing.JTextField();
        lb_numeroOAB = new javax.swing.JLabel();
        ckb_alterarNumeroOAB = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(lb_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });
        jPanel2.add(bt_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALTERAR COLABORADOR");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 720, 80));

        jPanelFundo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 100));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("ALTERAR");
        jPanelFundo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 700, 150, 50));

        txt_matricula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanelFundo.add(txt_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 180, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Matrícula:");
        jPanelFundo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ckb_alterarStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckb_alterarStatus.setText("Alterar");
        ckb_alterarStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_alterarStatusItemStateChanged(evt);
            }
        });
        jPanel1.add(ckb_alterarStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 80, -1));

        txt_telefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_telefone.setEnabled(false);
        jPanel1.add(txt_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 230, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Novo Telefone:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Novo Nome:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 100, -1));

        txt_nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nome.setEnabled(false);
        jPanel1.add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 230, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Novo Email:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, -1));

        txt_email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_email.setEnabled(false);
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 230, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rb_ativo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rb_ativo.setText("Ativo");
        rb_ativo.setEnabled(false);
        rb_ativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_ativoActionPerformed(evt);
            }
        });
        jPanel3.add(rb_ativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        rb_inativo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rb_inativo.setText("Inativo");
        rb_inativo.setEnabled(false);
        rb_inativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_inativoActionPerformed(evt);
            }
        });
        jPanel3.add(rb_inativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 240, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Novo Status:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 100, -1));

        ckb_alterarNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckb_alterarNome.setText("Alterar");
        ckb_alterarNome.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_alterarNomeItemStateChanged(evt);
            }
        });
        ckb_alterarNome.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckb_alterarNomeStateChanged(evt);
            }
        });
        jPanel1.add(ckb_alterarNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        ckb_alterarTelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckb_alterarTelefone.setText("Alterar");
        ckb_alterarTelefone.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_alterarTelefoneItemStateChanged(evt);
            }
        });
        jPanel1.add(ckb_alterarTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        ckb_alterarCargo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckb_alterarCargo.setText("Alterar");
        ckb_alterarCargo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_alterarCargoItemStateChanged(evt);
            }
        });
        ckb_alterarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_alterarCargoActionPerformed(evt);
            }
        });
        jPanel1.add(ckb_alterarCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        cb_cargo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cb_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADVOGADO", "ESTAGIÁRIO", "FUNCIONÁRIO" }));
        cb_cargo.setEnabled(false);
        cb_cargo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_cargoItemStateChanged(evt);
            }
        });
        jPanel1.add(cb_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 230, 30));

        lb_cargo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_cargo.setText("Novo Cargo:");
        jPanel1.add(lb_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 100, -1));

        ckb_alterarEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckb_alterarEmail.setText("Alterar");
        ckb_alterarEmail.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_alterarEmailItemStateChanged(evt);
            }
        });
        jPanel1.add(ckb_alterarEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        txt_numeroOAB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_numeroOAB.setEnabled(false);
        jPanel1.add(txt_numeroOAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 230, -1));

        lb_numeroOAB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_numeroOAB.setText("Novo Número Da OAB:");
        jPanel1.add(lb_numeroOAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 180, -1));

        ckb_alterarNumeroOAB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckb_alterarNumeroOAB.setText("Alterar");
        ckb_alterarNumeroOAB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_alterarNumeroOABItemStateChanged(evt);
            }
        });
        jPanel1.add(ckb_alterarNumeroOAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        jPanelFundo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 470, 500));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ALTERE OS DADOS");
        jPanelFundo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        getContentPane().add(jPanelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        this.setVisible(false);
        TelaColaboradores.main(null);
    }//GEN-LAST:event_bt_voltarActionPerformed

    private void rb_inativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_inativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_inativoActionPerformed

    private void rb_ativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_ativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_ativoActionPerformed

    private void cb_cargoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_cargoItemStateChanged
        JComboBox texto = (JComboBox) evt.getSource();
        if (! texto.getSelectedItem().toString().equalsIgnoreCase(
            "advogado")
        ) {
            txt_numeroOAB.setVisible(false);
            lb_numeroOAB.setVisible(false);
            ckb_alterarNumeroOAB.setVisible(false);
        }
        else {
            txt_numeroOAB.setVisible(true);
            lb_numeroOAB.setVisible(true);
            ckb_alterarNumeroOAB.setVisible(true);
        }
    }//GEN-LAST:event_cb_cargoItemStateChanged

    private void ckb_alterarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_alterarCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckb_alterarCargoActionPerformed

    private void ckb_alterarNomeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckb_alterarNomeStateChanged
                
    }//GEN-LAST:event_ckb_alterarNomeStateChanged

    private void ckb_alterarNomeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_alterarNomeItemStateChanged
        JCheckBox ckb = (JCheckBox) evt.getSource();
        if (ckb.isSelected()) {
            txt_nome.setEnabled(true);
        }
        else {
            txt_nome.setText("");
            txt_nome.setEnabled(false);
        }
    }//GEN-LAST:event_ckb_alterarNomeItemStateChanged

    private void ckb_alterarTelefoneItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_alterarTelefoneItemStateChanged
        JCheckBox ckb = (JCheckBox) evt.getSource();
        if (ckb.isSelected()) {
            txt_telefone.setEnabled(true);
        }
        else {
            txt_telefone.setText("");
            txt_telefone.setEnabled(false);
        }
    }//GEN-LAST:event_ckb_alterarTelefoneItemStateChanged

    private void ckb_alterarEmailItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_alterarEmailItemStateChanged
        JCheckBox ckb = (JCheckBox) evt.getSource();
        if (ckb.isSelected()) {
            txt_email.setEnabled(true);
        }
        else {
            txt_email.setText("");
            txt_email.setEnabled(false);
        }
    }//GEN-LAST:event_ckb_alterarEmailItemStateChanged

    private void ckb_alterarCargoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_alterarCargoItemStateChanged
        JCheckBox ckb = (JCheckBox) evt.getSource();
        if (ckb.isSelected()) {
            cb_cargo.setEnabled(true);
        }
        else {
            cb_cargo.setEnabled(false);
        }
    }//GEN-LAST:event_ckb_alterarCargoItemStateChanged

    private void ckb_alterarNumeroOABItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_alterarNumeroOABItemStateChanged
        JCheckBox ckb = (JCheckBox) evt.getSource();
        if (ckb.isSelected()) {
            txt_numeroOAB.setEnabled(true);
        }
        else {
            txt_numeroOAB.setEnabled(false);
        }
    }//GEN-LAST:event_ckb_alterarNumeroOABItemStateChanged

    private void ckb_alterarStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_alterarStatusItemStateChanged
        JCheckBox ckb = (JCheckBox) evt.getSource();
        if (ckb.isSelected()) {
            rb_ativo.setEnabled(true);
            rb_inativo.setEnabled(true);
        }
        else {
            rb_ativo.setEnabled(false);
            rb_inativo.setEnabled(false);
        }
    }//GEN-LAST:event_ckb_alterarStatusItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarColaborador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_voltar;
    private javax.swing.JComboBox<String> cb_cargo;
    private javax.swing.JCheckBox ckb_alterarCargo;
    private javax.swing.JCheckBox ckb_alterarEmail;
    private javax.swing.JCheckBox ckb_alterarNome;
    private javax.swing.JCheckBox ckb_alterarNumeroOAB;
    private javax.swing.JCheckBox ckb_alterarStatus;
    private javax.swing.JCheckBox ckb_alterarTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JLabel lb_cargo;
    private javax.swing.JLabel lb_numeroOAB;
    private javax.swing.JLabel lb_voltar;
    private javax.swing.JRadioButton rb_ativo;
    private javax.swing.JRadioButton rb_inativo;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_matricula;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_numeroOAB;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables
}
