/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.util.Iterator;
import model.Controller;
import model.IAutor;
import model.IController;
import model.ILivro;
import view.utils.*;

public class TelaLivros extends BaseWindow {

    /**
     * Creates new form TelaColaboradores
     */
    public TelaLivros() {
        super(null);
        initComponents();
        jPanel = jPanelFundo;
        aplicarConfiguracoes();
        carregarImagem(lb_voltar, "voltar.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        bt_deletarPorIsbn = new javax.swing.JButton();
        bt_deletarSelecionado = new javax.swing.JButton();
        bt_cadastrar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        bt_alterarPorId = new javax.swing.JButton();
        bt_alterarSelecionado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        bt_buscarPorAutor = new javax.swing.JButton();
        bt_buscarTodos = new javax.swing.JButton();
        bt_buscarPorEditora = new javax.swing.JButton();
        bt_buscarPorArea = new javax.swing.JButton();
        bt_buscarPorTitulo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lb_voltar = new javax.swing.JLabel();
        bt_voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TÍTULO", "ÁREA DO DIREITO", "AUTORES", "EDIÇÃO", "ANO DE PUBLICAÇÃO", "EDITORA", "STATUS", "ISBN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 1150, 210));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_deletarPorIsbn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_deletarPorIsbn.setText("DELETAR POR ISBN");
        bt_deletarPorIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletarPorIsbnActionPerformed(evt);
            }
        });
        jPanel3.add(bt_deletarPorIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 220, 40));

        bt_deletarSelecionado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_deletarSelecionado.setText("DELETAR SELECIONADO");
        bt_deletarSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletarSelecionadoActionPerformed(evt);
            }
        });
        jPanel3.add(bt_deletarSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 220, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, 260, 180));

        bt_cadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_cadastrar.setText("CADASTRAR");
        bt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 180, 140));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_alterarPorId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_alterarPorId.setText("ALTERAR POR ISBN");
        bt_alterarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarPorIdActionPerformed(evt);
            }
        });
        jPanel6.add(bt_alterarPorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 220, 40));

        bt_alterarSelecionado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_alterarSelecionado.setText("ALTERAR SELECIONADO");
        bt_alterarSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarSelecionadoActionPerformed(evt);
            }
        });
        jPanel6.add(bt_alterarSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 220, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 260, 180));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DELETAR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 260, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ALTERAR");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 260, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BUSCAR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 260, 30));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_buscarPorAutor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_buscarPorAutor.setText("POR AUTOR");
        bt_buscarPorAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarPorAutorActionPerformed(evt);
            }
        });
        jPanel7.add(bt_buscarPorAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 230, 30));

        bt_buscarTodos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_buscarTodos.setText("TODOS");
        bt_buscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarTodosActionPerformed(evt);
            }
        });
        jPanel7.add(bt_buscarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        bt_buscarPorEditora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_buscarPorEditora.setText("POR EDITORA");
        bt_buscarPorEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarPorEditoraActionPerformed(evt);
            }
        });
        jPanel7.add(bt_buscarPorEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 230, 30));

        bt_buscarPorArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_buscarPorArea.setText("POR ÁREA");
        bt_buscarPorArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarPorAreaActionPerformed(evt);
            }
        });
        jPanel7.add(bt_buscarPorArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 30));

        bt_buscarPorTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_buscarPorTitulo.setText("POR TÍTULO");
        bt_buscarPorTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarPorTituloActionPerformed(evt);
            }
        });
        jPanel7.add(bt_buscarPorTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 230, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 260, 180));

        jPanelFundo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1190, 570));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(lb_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });
        jPanel2.add(bt_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIVROS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1210, 80));

        jPanelFundo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 100));

        getContentPane().add(jPanelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        this.setVisible(false);
        TelaMenuLivro.main(null);
    }//GEN-LAST:event_bt_voltarActionPerformed

    private void bt_deletarPorIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletarPorIsbnActionPerformed
        
        try {                        
                                                            
            String isbn = getStringFromUser("Digite o ISBN do livro");
            
            if (isbn == null) return;
            
            IController controller = Controller.getInstance();
            if (! controller.existeLivro(isbn))
                throw new Exception("livro não cadastrado!");
            
            controller.removerLivro(isbn);
            
            exibirMensagemInformativa("Livro deletado com sucesso!");
            
            
        } catch(Exception e) {
            exibirMesagemDeErro(e.getMessage());
        }
    }//GEN-LAST:event_bt_deletarPorIsbnActionPerformed

    private void bt_deletarSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletarSelecionadoActionPerformed
        
        try {
            
            if (!exibirMensagemConfirmacao("Tem certeza que deseja excluir o livro?"))
                return;
            
            Iterator<Object> linha = getLinhaSelecionada(table);
            
            if (! linha.hasNext())
                throw new Exception("Selecione um registro primeiro");
            
            for (int i = 0; i < 7 && linha.hasNext(); i++) {
                linha.next();                
            }
            
            String isbn = linha.next().toString();            
            
            IController controller = Controller.getInstance();
            if (! controller.existeLivro(isbn))
                throw new Exception("livro não cadastrado!");
            
            controller.removerLivro(isbn);
            
            exibirMensagemInformativa("Livro deletado com sucesso!");
            
            
        } catch(Exception e) {
            exibirMesagemDeErro(e.getMessage());
        }
    }//GEN-LAST:event_bt_deletarSelecionadoActionPerformed

    private void bt_alterarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarPorIdActionPerformed
        this.setVisible(false);
        TelaAlterarLivros.main(null);
    }//GEN-LAST:event_bt_alterarPorIdActionPerformed

    private void bt_alterarSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarSelecionadoActionPerformed
        this.setVisible(false);
        TelaAlterarLivros.main(null);
    }//GEN-LAST:event_bt_alterarSelecionadoActionPerformed

    private void bt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarActionPerformed
        this.setVisible(false);
        TelaCadastrarLivros.main(null);
    }//GEN-LAST:event_bt_cadastrarActionPerformed

    private void bt_buscarPorAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarPorAutorActionPerformed
        try {
            IController controller = Controller.getInstance();
            int idAutor = getIntFromUser("Digite o id do autor do livro: ");
            if (idAutor == -1) return;
                            
            Iterator<ILivro> livros = controller.getLivroPorAutor(idAutor);
            var livrosTabela = converIteratorToObject(livros);
            listarItens(table, livrosTabela);
            
        } catch(Exception erro) {
            exibirMesagemDeErro(erro.getMessage());
        }
    }//GEN-LAST:event_bt_buscarPorAutorActionPerformed

    private void bt_buscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarTodosActionPerformed
        try {
            IController controller = Controller.getInstance();
            Iterator<ILivro> livros = controller.getTodosLivros();
            var livrosTabela = converIteratorToObject(livros);
            listarItens(table, livrosTabela);
            
        } catch(Exception erro) {
            exibirMesagemDeErro(erro.getMessage());
        }
    }//GEN-LAST:event_bt_buscarTodosActionPerformed

    private void bt_buscarPorEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarPorEditoraActionPerformed
        
        try {
            IController controller = Controller.getInstance();
            int idEditora = getIntFromUser("Digite o id da editora do livro: ");
            if (idEditora == -1) return;
            
            if (! controller.existeEditora(idEditora))
                throw new Exception("Esta editora não está cadastrada");
                            
            Iterator<ILivro> livros = controller.getLivroPorEditora(idEditora);
            var livrosTabela = converIteratorToObject(livros);
            listarItens(table, livrosTabela);
            
        } catch(Exception erro) {
            exibirMesagemDeErro(erro.getMessage());
        }
    }//GEN-LAST:event_bt_buscarPorEditoraActionPerformed

    private void bt_buscarPorAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarPorAreaActionPerformed
        try {
            IController controller = Controller.getInstance();
            int idAreaDireito = getIntFromUser("Digite o id da área do direito do livro: ");
            if (idAreaDireito == -1) return;
            
            if (! controller.existeAreaDireito(idAreaDireito))
                throw new Exception("Esta área do direito não está cadastrada");
                            
            Iterator<ILivro> livros = controller.getLivroPorArea(idAreaDireito);
            var livrosTabela = converIteratorToObject(livros);
            listarItens(table, livrosTabela);
            
        } catch(Exception erro) {
            exibirMesagemDeErro(erro.getMessage());
        }
    }//GEN-LAST:event_bt_buscarPorAreaActionPerformed

    private void bt_buscarPorTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarPorTituloActionPerformed
        
        try {
            IController controller = Controller.getInstance();
            String titulo = getStringFromUser("Digite o título do livro:");
            if (titulo == null) return;                        
                            
            Iterator<ILivro> livros = controller.getLivroPorTitulo(titulo.trim());
            var livrosTabela = converIteratorToObject(livros);
            listarItens(table, livrosTabela);
            
        } catch(Exception erro) {
            exibirMesagemDeErro(erro.getMessage());
        }
    }//GEN-LAST:event_bt_buscarPorTituloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_alterarPorId;
    private javax.swing.JButton bt_alterarSelecionado;
    private javax.swing.JButton bt_buscarPorArea;
    private javax.swing.JButton bt_buscarPorAutor;
    private javax.swing.JButton bt_buscarPorEditora;
    private javax.swing.JButton bt_buscarPorTitulo;
    private javax.swing.JButton bt_buscarTodos;
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JButton bt_deletarPorIsbn;
    private javax.swing.JButton bt_deletarSelecionado;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_voltar;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    @Override
    protected Object[] templedMethodObjectType(Object obj) {
        
        ILivro livro = (ILivro) obj;
        String status = "ativo";
        
        if (livro.estaAbsoleto())
            status = "inativo";
        
        Iterator<IAutor> autores = livro.getAutoresLivro();
        String autores_str = "";
        
        while(autores.hasNext()) {
            autores_str += autores.next().getNome();
            
            if (autores.hasNext())
                autores_str += " / ";
        }
        
        return new Object[] {
            livro.getTitulo(),
            livro.getAreaDireito().getNome(),
            autores_str,
            livro.getEdicao(),
            livro.getAnoPublicacao(),
            livro.getEditora().getNome(),
            status,
            livro.getISBN()
        };
    }





}
