/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JCheckBox;
import model.Controller;
import model.Editora;
import model.IAreaDireito;
import model.IAutor;
import model.IController;
import model.IEditora;
import model.ILivro;
import model.Livro;
import view.utils.BaseWindow;


public class TelaAlterarLivros extends BaseWindow {

    ArrayList<IAutor> autores = null;
    
    public TelaAlterarLivros(Object isbn) {
        super(null);
        initComponents();
        jPanel = jPanelFundo;
        aplicarConfiguracoes();
        carregarImagem(lb_voltar, "voltar.png");
        
        if (isbn != null) {
            txt_isbn.setText(isbn.toString());
            txt_isbn.setEnabled(false);
            
        }
        
        autores = new ArrayList<IAutor>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lb_voltar = new javax.swing.JLabel();
        bt_voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bt_alterar = new javax.swing.JButton();
        txt_isbn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ckb_alterarStatus = new javax.swing.JCheckBox();
        txt_areaDireito = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_editora = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        rb_ativo = new javax.swing.JRadioButton();
        rb_inativo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        ckb_alterarTitulo = new javax.swing.JCheckBox();
        ckb_alterarEdicao = new javax.swing.JCheckBox();
        ckb_alterarAreaDireito = new javax.swing.JCheckBox();
        lb_cargo = new javax.swing.JLabel();
        ckb_alterarAnoPublicacao = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txt_novoIsbn = new javax.swing.JTextField();
        ckb_alterarIsbn = new javax.swing.JCheckBox();
        lb_cargo1 = new javax.swing.JLabel();
        ckb_alterarEditora = new javax.swing.JCheckBox();
        txt_edicao = new javax.swing.JTextField();
        txt_anoPublicacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bt_adicionarAutor = new javax.swing.JButton();
        bt_removerAutor = new javax.swing.JButton();
        bt_refresh = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ckb_alterarAutores = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(lb_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });
        jPanel2.add(bt_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALTERAR LIVRO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1080, 80));

        jPanelFundo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 100));

        bt_alterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_alterar.setText("ALTERAR");
        bt_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarActionPerformed(evt);
            }
        });
        jPanelFundo.add(bt_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 690, 150, 50));

        txt_isbn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanelFundo.add(txt_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 180, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ISBN:");
        jPanelFundo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ckb_alterarStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckb_alterarStatus.setText("Alterar");
        ckb_alterarStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_alterarStatusItemStateChanged(evt);
            }
        });
        jPanel1.add(ckb_alterarStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 80, -1));

        txt_areaDireito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_areaDireito.setEnabled(false);
        jPanel1.add(txt_areaDireito, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 230, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nova Edição:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 100, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Novo Título:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 100, -1));

        txt_titulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_titulo.setEnabled(false);
        jPanel1.add(txt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 230, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Novo Ano de Publicação:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, -1));

        txt_editora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_editora.setEnabled(false);
        jPanel1.add(txt_editora, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 230, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rb_ativo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rb_ativo.setText("Ativo");
        rb_ativo.setEnabled(false);
        rb_ativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_ativoActionPerformed(evt);
            }
        });
        jPanel3.add(rb_ativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        rb_inativo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rb_inativo.setText("Inativo");
        rb_inativo.setEnabled(false);
        rb_inativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_inativoActionPerformed(evt);
            }
        });
        jPanel3.add(rb_inativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 340, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Novo Status:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 100, -1));

        ckb_alterarTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckb_alterarTitulo.setText("Alterar");
        ckb_alterarTitulo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_alterarTituloItemStateChanged(evt);
            }
        });
        ckb_alterarTitulo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckb_alterarTituloStateChanged(evt);
            }
        });
        jPanel1.add(ckb_alterarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        ckb_alterarEdicao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckb_alterarEdicao.setText("Alterar");
        ckb_alterarEdicao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_alterarEdicaoItemStateChanged(evt);
            }
        });
        jPanel1.add(ckb_alterarEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        ckb_alterarAreaDireito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckb_alterarAreaDireito.setText("Alterar");
        ckb_alterarAreaDireito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_alterarAreaDireitoItemStateChanged(evt);
            }
        });
        ckb_alterarAreaDireito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_alterarAreaDireitoActionPerformed(evt);
            }
        });
        jPanel1.add(ckb_alterarAreaDireito, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        lb_cargo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_cargo.setText("Nova Área Do DIreito:");
        jPanel1.add(lb_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 160, -1));

        ckb_alterarAnoPublicacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckb_alterarAnoPublicacao.setText("Alterar");
        ckb_alterarAnoPublicacao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_alterarAnoPublicacaoItemStateChanged(evt);
            }
        });
        jPanel1.add(ckb_alterarAnoPublicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Novo ISBN:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 90, -1));

        txt_novoIsbn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_novoIsbn.setEnabled(false);
        jPanel1.add(txt_novoIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 230, -1));

        ckb_alterarIsbn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckb_alterarIsbn.setText("Alterar");
        ckb_alterarIsbn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_alterarIsbnItemStateChanged(evt);
            }
        });
        ckb_alterarIsbn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckb_alterarIsbnStateChanged(evt);
            }
        });
        jPanel1.add(ckb_alterarIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        lb_cargo1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_cargo1.setText("Nova Editora:");
        jPanel1.add(lb_cargo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 100, -1));

        ckb_alterarEditora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckb_alterarEditora.setText("Alterar");
        ckb_alterarEditora.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_alterarEditoraItemStateChanged(evt);
            }
        });
        ckb_alterarEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_alterarEditoraActionPerformed(evt);
            }
        });
        jPanel1.add(ckb_alterarEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        txt_edicao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_edicao.setEnabled(false);
        jPanel1.add(txt_edicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 230, -1));

        txt_anoPublicacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_anoPublicacao.setEnabled(false);
        jPanel1.add(txt_anoPublicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 230, -1));

        jPanelFundo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 550, 500));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("AUTORES");
        jPanelFundo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 70, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "NOME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setEnabled(false);
        jScrollPane1.setViewportView(table);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 350, 180));

        bt_adicionarAutor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_adicionarAutor.setText("ADICIONAR AUTOR");
        bt_adicionarAutor.setEnabled(false);
        bt_adicionarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_adicionarAutorActionPerformed(evt);
            }
        });
        jPanel4.add(bt_adicionarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 170, 30));

        bt_removerAutor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_removerAutor.setText("REMOVER AUTOR");
        bt_removerAutor.setEnabled(false);
        bt_removerAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_removerAutorActionPerformed(evt);
            }
        });
        jPanel4.add(bt_removerAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 160, 30));

        bt_refresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_refresh.setText("refresh");
        bt_refresh.setEnabled(false);
        bt_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_refreshActionPerformed(evt);
            }
        });
        jPanel4.add(bt_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jPanelFundo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 400, 300));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("ALTERE OS DADOS");
        jPanelFundo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        ckb_alterarAutores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckb_alterarAutores.setText("Alterar");
        ckb_alterarAutores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_alterarAutoresItemStateChanged(evt);
            }
        });
        jPanelFundo.add(ckb_alterarAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 90, -1));

        getContentPane().add(jPanelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        this.setVisible(false);
        TelaLivros.main(null);
    }//GEN-LAST:event_bt_voltarActionPerformed

    private void rb_inativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_inativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_inativoActionPerformed

    private void rb_ativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_ativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_ativoActionPerformed

    private void ckb_alterarAreaDireitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_alterarAreaDireitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckb_alterarAreaDireitoActionPerformed

    private void ckb_alterarTituloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckb_alterarTituloStateChanged
                
    }//GEN-LAST:event_ckb_alterarTituloStateChanged

    private void ckb_alterarTituloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_alterarTituloItemStateChanged
        JCheckBox ckb = (JCheckBox) evt.getSource();
        if (ckb.isSelected()) {
            txt_titulo.setEnabled(true);
        }
        else {
            txt_titulo.setText("");
            txt_titulo.setEnabled(false);
        }
    }//GEN-LAST:event_ckb_alterarTituloItemStateChanged

    private void ckb_alterarEdicaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_alterarEdicaoItemStateChanged
        JCheckBox ckb = (JCheckBox) evt.getSource();
        if (ckb.isSelected()) {
            txt_edicao.setEnabled(true);
        }
        else {
            txt_edicao.setText("");
            txt_edicao.setEnabled(false);
        }
    }//GEN-LAST:event_ckb_alterarEdicaoItemStateChanged

    private void ckb_alterarAnoPublicacaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_alterarAnoPublicacaoItemStateChanged
        JCheckBox ckb = (JCheckBox) evt.getSource();
        if (ckb.isSelected()) {
            txt_anoPublicacao.setEnabled(true);
        }
        else {
            txt_anoPublicacao.setText("");
            txt_anoPublicacao.setEnabled(false);
        }
    }//GEN-LAST:event_ckb_alterarAnoPublicacaoItemStateChanged

    private void ckb_alterarAreaDireitoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_alterarAreaDireitoItemStateChanged
        JCheckBox ckb = (JCheckBox) evt.getSource();
        if (ckb.isSelected()) {
            txt_areaDireito.setEnabled(true);
        }
        else {
            txt_areaDireito.setEnabled(false);
        }
    }//GEN-LAST:event_ckb_alterarAreaDireitoItemStateChanged

    private void ckb_alterarStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_alterarStatusItemStateChanged
        JCheckBox ckb = (JCheckBox) evt.getSource();
        if (ckb.isSelected()) {
            rb_ativo.setEnabled(true);
            rb_inativo.setEnabled(true);
        }
        else {
            rb_ativo.setEnabled(false);
            rb_inativo.setEnabled(false);
        }
    }//GEN-LAST:event_ckb_alterarStatusItemStateChanged

    private void ckb_alterarIsbnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_alterarIsbnItemStateChanged
        JCheckBox ckb = (JCheckBox) evt.getSource();
        if (ckb.isSelected()) {
            txt_novoIsbn.setEnabled(true);            
        }
        else {
            txt_novoIsbn.setEnabled(false);
        }
    }//GEN-LAST:event_ckb_alterarIsbnItemStateChanged

    private void ckb_alterarIsbnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckb_alterarIsbnStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ckb_alterarIsbnStateChanged

    private void ckb_alterarEditoraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_alterarEditoraItemStateChanged
        
        JCheckBox ckb = (JCheckBox) evt.getSource();
        if (ckb.isSelected()) {
            txt_editora.setEnabled(true);
        }
        else {
            txt_editora.setEnabled(false);
        }
    }//GEN-LAST:event_ckb_alterarEditoraItemStateChanged

    private void ckb_alterarEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_alterarEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckb_alterarEditoraActionPerformed

    private void ckb_alterarAutoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_alterarAutoresItemStateChanged
        
        try {
            JCheckBox ckb = (JCheckBox) evt.getSource();
            if (ckb.isSelected()) {
                table.setEnabled(true);
                bt_adicionarAutor.setEnabled(true);
                bt_removerAutor.setEnabled(true);
                bt_refresh.setEnabled(true);
            }
            else {
                limparTabela(table);
                table.setEnabled(false);
                bt_adicionarAutor.setEnabled(false);
                bt_removerAutor.setEnabled(false);
                bt_refresh.setEnabled(false);
                autores.clear();            
            }
        
        } catch (Exception e) {
            exibirMesagemDeErro(e.getMessage());
        }
    }//GEN-LAST:event_ckb_alterarAutoresItemStateChanged

    private void bt_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_refreshActionPerformed
        try {
            
            autores.clear();
            limparTabela(table);
            
            IController controller = Controller.getInstance();
            
            String isbn = txt_isbn.getText();
            ILivro livro = controller.getLivro(isbn);
            
            Iterator<IAutor> autoresLivro = controller.getAutoresDoLivro(livro);
            
            while (autoresLivro.hasNext())
                autores.add(autoresLivro.next());
            
            var autoresTabela = converIteratorToObject(autores.iterator());
            listarItens(table, autoresTabela);
            
        } catch(Exception e) {
            exibirMesagemDeErro(e.getMessage());
        }
    }//GEN-LAST:event_bt_refreshActionPerformed

    private void bt_adicionarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_adicionarAutorActionPerformed
        try {
            IController controller = Controller.getInstance();
            int idAutor = getIntFromUser("Digite o id do autor");
            
            if (! controller.existeAutor(idAutor))
                throw new Exception("Autor não cadastrado");
            
            IAutor autor = controller.getAutor(idAutor);
            
            if (autores.contains(autor)) {
                throw new Exception("Autor já está na lista");
            }
            autores.add(autor);
            
            var it = autores.iterator();
            var itTabela = converIteratorToObject(it);
            listarItens(table, itTabela);
            
        } catch (Exception e) {
            exibirMesagemDeErro(e.getMessage());
        }
    }//GEN-LAST:event_bt_adicionarAutorActionPerformed

    private void bt_removerAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_removerAutorActionPerformed
        try {
            IController controller = Controller.getInstance();
            int idAutor = getIntFromUser("Digite o id do autor");
            
            if (! controller.existeAutor(idAutor))
                throw new Exception("Autor não cadastrado");
            
            IAutor autor = controller.getAutor(idAutor);
            
            if (! autores.contains(autor)) {
                throw new Exception("Autor não está na lista!");
            }
            
            autores.remove(autor);
            
            var it = autores.iterator();
            var itTabela = converIteratorToObject(it);
            listarItens(table, itTabela);
            
        } catch (Exception e) {
            exibirMesagemDeErro(e.getMessage());
        }
    }//GEN-LAST:event_bt_removerAutorActionPerformed

    private void bt_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarActionPerformed
        try {
            
            IController controller = Controller.getInstance();
            String isbnAtual = txt_isbn.getText();
            ILivro livro = controller.getLivro(isbnAtual);            
            
            if (ckb_alterarIsbn.isSelected())
                livro.setISBN(txt_novoIsbn.getText());
            
            if (ckb_alterarTitulo.isSelected())
                livro.setTitulo(txt_titulo.getText());
            
            if (ckb_alterarEdicao.isSelected())
                livro.setEdicao(Integer.parseInt(txt_edicao.getText()));
            
            if (ckb_alterarAreaDireito.isSelected()) {                
                int idAreaDireito = (Integer.parseInt(txt_areaDireito.getText()));
                IAreaDireito areaDireito = controller.getAreaDireito(idAreaDireito);
                livro.setAreaDireito(areaDireito);
            }
            
            if (ckb_alterarAnoPublicacao.isSelected())
                livro.setAnoPublicacao(strToDate(txt_anoPublicacao.getText()));
            
            if (ckb_alterarEditora.isSelected()) {
                int idEditora = Integer.parseInt(txt_editora.getText());
                IEditora editora = controller.getEditora(idEditora);
                livro.setEditora(editora);
            }
            
            if (ckb_alterarStatus.isSelected()) {
                if (rb_ativo.isSelected())
                    livro.setEstaAbsoleto(false);
                if (rb_inativo.isSelected())
                    livro.setEstaAbsoleto(true);
            }
            
            if (ckb_alterarAutores.isSelected()) {
                livro.setAutoresLivro(autores.iterator());
            }
                
            
            controller.alterarLivro(isbnAtual, livro);
            
            exibirMensagemInformativa("Livro alterado com sucesso!");
            
            
            
        } catch(Exception e) {
            exibirMesagemDeErro(e.getMessage());
        }
    }//GEN-LAST:event_bt_alterarActionPerformed

    /**
     * @param isbn
     * @param args the command line arguments
     */
    public static void main(Object isbn) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarLivros(isbn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_adicionarAutor;
    private javax.swing.JButton bt_alterar;
    private javax.swing.JButton bt_refresh;
    private javax.swing.JButton bt_removerAutor;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JCheckBox ckb_alterarAnoPublicacao;
    private javax.swing.JCheckBox ckb_alterarAreaDireito;
    private javax.swing.JCheckBox ckb_alterarAutores;
    private javax.swing.JCheckBox ckb_alterarEdicao;
    private javax.swing.JCheckBox ckb_alterarEditora;
    private javax.swing.JCheckBox ckb_alterarIsbn;
    private javax.swing.JCheckBox ckb_alterarStatus;
    private javax.swing.JCheckBox ckb_alterarTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_cargo;
    private javax.swing.JLabel lb_cargo1;
    private javax.swing.JLabel lb_voltar;
    private javax.swing.JRadioButton rb_ativo;
    private javax.swing.JRadioButton rb_inativo;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_anoPublicacao;
    private javax.swing.JTextField txt_areaDireito;
    private javax.swing.JTextField txt_edicao;
    private javax.swing.JTextField txt_editora;
    private javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_novoIsbn;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables

    @Override
    protected Object[] templedMethodObjectType(Object obj) {
        
        IAutor autor = (IAutor) obj;
        
        return new Object[] {
            autor.getId(),
            autor.getNome()
        };
    }





}
