/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.Date;
import model.Controller;
import model.IAreaDireito;
import model.IAutor;
import model.IController;
import model.IEditora;
import model.ILivro;
import model.Livro;
import view.utils.BaseWindow;


public class TelaCadastrarLivros extends BaseWindow {

    
    private ArrayList<IAutor> autores = null;
    
    public TelaCadastrarLivros() {
        super(null);
        initComponents();
        jPanel = jPanelFundo;
        aplicarConfiguracoes();
        carregarImagem(lb_voltar, "voltar.png");
        
        autores = new ArrayList<IAutor>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lb_voltar = new javax.swing.JLabel();
        bt_voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_isbn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_anoPublicacao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_idAreaDireito = new javax.swing.JTextField();
        txt_titulo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_edicao = new javax.swing.JTextField();
        txt_idEditora = new javax.swing.JTextField();
        bt_cadastrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bt_removerAutor = new javax.swing.JButton();
        bt_adicionarAutor = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(lb_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });
        jPanel2.add(bt_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRAR LIVRO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1100, 80));

        jPanelFundo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 100));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_isbn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txt_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 320, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Ano Publicação:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 130, -1));

        txt_anoPublicacao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txt_anoPublicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 320, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("ISBN:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 50, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Edição:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 70, -1));

        txt_idAreaDireito.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txt_idAreaDireito, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 320, 30));

        txt_titulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 320, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Título:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 60, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("ID da Editora:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 100, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("ID daÁrea Do Direito:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 150, -1));

        txt_edicao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txt_edicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 320, 30));

        txt_idEditora.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txt_idEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 320, 30));

        jPanelFundo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 560, 310));

        bt_cadastrar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bt_cadastrar.setText("CADASTRAR");
        bt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarActionPerformed(evt);
            }
        });
        jPanelFundo.add(bt_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 500, 210, 50));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 400, 180));

        bt_removerAutor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_removerAutor.setText("REMOVER AUTOR");
        bt_removerAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_removerAutorActionPerformed(evt);
            }
        });
        jPanel3.add(bt_removerAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 180, 40));

        bt_adicionarAutor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_adicionarAutor.setText("ADICIONAR AUTOR");
        bt_adicionarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_adicionarAutorActionPerformed(evt);
            }
        });
        jPanel3.add(bt_adicionarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 43, 180, 40));

        jPanelFundo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 440, 310));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("AUTORES");
        jPanelFundo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 260, 30));

        getContentPane().add(jPanelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        this.setVisible(false);
        TelaLivros.main(null);
    }//GEN-LAST:event_bt_voltarActionPerformed

    private void bt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarActionPerformed
        try {
            IController controller = Controller.getInstance();
            String isbn = txt_isbn.getText();
            String titulo = txt_titulo.getText();
            Date anoPublicacao = strToDate(txt_anoPublicacao.getText());
            int edicao = Integer.parseInt(txt_edicao.getText());
            int idEditora = Integer.parseInt(txt_idEditora.getText());
            int idAreaDireito = Integer.parseInt(txt_idAreaDireito.getText());                        
            
            IEditora editora = controller.getEditora(idEditora);
            IAreaDireito areaDireito = controller.getAreaDireito(idAreaDireito);
            
            
            ILivro livro = new Livro();
            livro.setISBN(isbn);
            livro.setTitulo(titulo);
            livro.setAnoPublicacao(anoPublicacao);
            livro.setEdicao(edicao);
            livro.setAreaDireito(areaDireito);
            livro.setEditora(editora);
            livro.setAutoresLivro(autores.iterator());
            
            controller.criarLivro(livro);
            
            exibirMensagemInformativa("Livro cadastrado com sucesso!");
            txt_isbn.setText("");
            txt_titulo.setText("");
            txt_anoPublicacao.setText("");
            txt_edicao.setText("");
            txt_idEditora.setText("");
            txt_idAreaDireito.setText("");
            
            autores.clear();
            limparTabela(table);
            
            
        } catch(Exception e) {
            exibirMesagemDeErro(e.getMessage());
        }
    }//GEN-LAST:event_bt_cadastrarActionPerformed

    private void bt_adicionarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_adicionarAutorActionPerformed
        try {
            IController controller = Controller.getInstance();
            int idAutor = getIntFromUser("Digite o id do autor");
            
            if (! controller.existeAutor(idAutor))
                throw new Exception("Autor não cadastrado");
            
            IAutor autor = controller.getAutor(idAutor);
            
            if (autores.contains(autor)) {
                throw new Exception("Autor já está na lista");
            }
            autores.add(autor);
            
            var it = autores.iterator();
            var itTabela = converIteratorToObject(it);
            listarItens(table, itTabela);
            
        } catch (Exception e) {
            exibirMesagemDeErro(e.getMessage());
        }
    }//GEN-LAST:event_bt_adicionarAutorActionPerformed

    private void bt_removerAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_removerAutorActionPerformed
        
        try {
            IController controller = Controller.getInstance();
            int idAutor = getIntFromUser("Digite o id do autor");
            
            if (! controller.existeAutor(idAutor))
                throw new Exception("Autor não cadastrado");
            
            IAutor autor = controller.getAutor(idAutor);
            
            if (! autores.contains(autor)) {
                throw new Exception("Autor não está na lista!");
            }
            
            autores.remove(autor);
            
            var it = autores.iterator();
            var itTabela = converIteratorToObject(it);
            listarItens(table, itTabela);
            
        } catch (Exception e) {
            exibirMesagemDeErro(e.getMessage());
        }
    }//GEN-LAST:event_bt_removerAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_adicionarAutor;
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JButton bt_removerAutor;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_voltar;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_anoPublicacao;
    private javax.swing.JTextField txt_edicao;
    private javax.swing.JTextField txt_idAreaDireito;
    private javax.swing.JTextField txt_idEditora;
    private javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables

    @Override
    protected Object[] templedMethodObjectType(Object obj) {
        
        IAutor autor = (IAutor) obj;
        
        return new Object[] {
            autor.getId(),
            autor.getNome()
        };
    }





}
