/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.utils;

import java.awt.Component;
import java.awt.Container;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Base2 extends javax.swing.JFrame {

    
    private final String pastaImagem = "./src/view/img/";
    
    public Base2() {
        initComponents();
        configurarCores();
        configurarPosicoes();
        setarLogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jPanelTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTitle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Título");
        jPanelTitle.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1230, 40));

        jPanelFundo.add(jPanelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 70));

        getContentPane().add(jPanelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Base2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Base2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Base2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Base2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Base2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JPanel jPanelTitle;
    // End of variables declaration//GEN-END:variables


    private void configurarCores() {
        jPanelFundo.setBackground(PaletaCores.FUNDO);
        
        configurarTemaBotes(jPanelFundo);
        configurarTemaPanels(jPanelFundo);
    }
    
    private void configurarTemaPanels(Container container) {
        Component[] componentes = container.getComponents();
        
        for (var componente : componentes) {
            if (componente instanceof JPanel) {
                JPanel panel = (JPanel) componente;
                
                panel.setBorder(
                        BorderFactory.createLineBorder(
                                PaletaCores.PANEL_BORDA,
                                3
                        )
                );
                
                panel.setBackground(PaletaCores.PANEL_FUNDO);
                configurarTemaPanels((Container) componente);                
            }
        }
    }
    
    private void configurarTemaBotes(Container container) {
        Component[] componentes = container.getComponents();
        
        for (var componente : componentes) {
            if (componente instanceof JButton) {
                componente.setBackground(PaletaCores.BOTAO);
                
                ((JButton) componente).addMouseListener(new MouseAdapter() {
                    
                    @Override
                    public void mouseEntered(MouseEvent e) {
                        mouseEntrarBotao(e);
                    }
                    
                    @Override
                    public void mouseExited(MouseEvent e) {
                        mouseSairBotao(e);
                    }
                    
                    @Override
                    public void mousePressed(MouseEvent e) {
                        mousePressedBotao(e);
                    }
                    
                    @Override
                    public void mouseReleased(MouseEvent e) {
                        mouseReleasedBotao(e);
                    }
                });
                
            }
            else if (componente instanceof JPanel) {
                configurarTemaBotes((Container) componente);
            }
        }
    }
    
    private void mouseReleasedBotao(MouseEvent evt) {
        JButton botao = (JButton) evt.getSource();
        botao.setBackground(PaletaCores.BOTAO_RELEASED);
        botao.setForeground(PaletaCores.TEXTO_FONTE);
    }
    
    private void mousePressedBotao(MouseEvent evt) {
        JButton botao = (JButton) evt.getSource();
        botao.setBackground(PaletaCores.BOTAO_CLICK);
        botao.setForeground(PaletaCores.BOTAO);
    }
    
    private void mouseEntrarBotao(MouseEvent evt) {
        JButton botao = (JButton) evt.getSource();
        botao.setBackground(PaletaCores.BOTAO_ENTER);
    }
    
    private void mouseSairBotao(MouseEvent evt) {
        JButton botao = (JButton) evt.getSource();
        botao.setBackground(PaletaCores.BOTAO);
    }
    
    private void configurarPosicoes() {
        this.setLocationRelativeTo(null);
    }

    private void setarLogo() {
        try {
            
            String caminho = pastaImagem + "logo_512.png";
            BufferedImage logo = ImageIO.read(new File(caminho));
            
            setIconImage(logo);
            
        } catch (IOException e) {
            exibirMesagemDeErro(
                    "Erro: não foi possível carregar a imagem"
            );
        
        } catch (Exception e) {
            exibirMesagemDeErro(e.getMessage());
        }
        
        
    }
    
    private void exibirMesagemDeErro(String mensagem) {
        JOptionPane.showMessageDialog(
                rootPane,
                mensagem,
                "ERRO",
                JOptionPane.ERROR_MESSAGE
        );
    }
    
    private void exibirMensagemInformativa(String mensagem) {
        JOptionPane.showMessageDialog(
                rootPane,
                mensagem,
                "ERRO",
                JOptionPane.INFORMATION_MESSAGE
        );
    }
}
